#!perl

# FRAGMENT id=shcompgen-hint command=untabify

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use App::tabify;

App::tabify::parse_cmdline();
App::tabify::run('untabify');

1;
# ABSTRACT: Convert tabs to spaces
# PODNAME:

=head1 SYNOPSIS

 untabify [OPTION]... <FILES...>


=head1 DESCRIPTION


=head1 OPTIONS

=over

=item * --tab-width=i, -w (default: 8)

Set tab width.

=item * --(no)indent-only

Not yet implemented.

By default C<untabify> will convert all tabs to spaces. Use C<--indent-only> to
only convert tabs that are at the beginning of lines.

=back


=head1 EXIT CODES

0 on success.

255 on I/O error.

99 on command-line options error.


=head1 FAQ


=head1 SEE ALSO

L<tabify>

=cut
